# -*- coding: utf-8 -*-
"""cocForGit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hllfpvdXS-J7xO1R2NIeown6NYFX7KIU
"""

import json
import os
import gspread
from google.oauth2.service_account import Credentials
from gspread_dataframe import set_with_dataframe
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

service_account_info = json.loads(os.environ["COCUSVJSONKEY"])

# Google Sheets Auth ----------
scopes = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

creds = Credentials.from_service_account_info(
    service_account_info,
    scopes=scopes
)

gc = gspread.authorize(creds)

# Open the existing spreadsheet by name
# Make sure a file named 'Existing_Sheet_Name' exists in your Google Drive
sh = gc.open('COC_Daily_Report')

cocUsers = pd.read_csv("data/COC UserDetails 28apr2026.csv")

#pip install pandas sqlalchemy pymysql

#from sqlalchemy import create_engine

# # connection details
# username = 'abhijeet'
# password = '9U3Ws1P8a8Stne3t'
# host = 'https://godbp.goqii.com'
# port = '3306'
# database = 'goqii_goqii'

# # create engine
# engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# # read table into dataframe
# cocUsers = pd.read_sql("""SELECT
#     u.userid,
#     u.mobile, u.email,
#     CONCAT(u.firstname,' ', u.lastname) AS name, u.status,
#     u.corporateid,
#     u.coachid,
#     u.expertid,
#     CONCAT(c.firstname,' ', c.lastname) AS coach,
#     CONCAT(ex.firstname,' ', ex.lastname) AS expert,
#     u.registrationDate,
#     u.sessiontime as last_app_open,
#     u.subscriptionstartdate,
#     u.subscriptionenddate,
#     e.coachingstartdate,
#     e.coachingenddate,
#     (CASE
#         WHEN e.currentEngagement = 0 THEN 'Passive'
#         WHEN e.currentEngagement = 1 THEN 'low'
#         WHEN e.currentEngagement = 2 THEN 'medium'
#         WHEN e.currentEngagement = 3 THEN 'High'
#         WHEN e.currentEngagement = 4 THEN 'Wow'
#     END) AS EngagementType,
#     u.callIntro, u.callIntroDate, u.callIntroRemender,
#     m.userMsgCount, m.coachMsgCount, m.expertMsgCount, m.lastUserMsg,
#     cl.attemptedCallsCount, cl.completedCallsCount, cl.lastCallDate,
#     cl.sumOfIntroCallDuration, cl.maxOfIntroCallDuration,
#     l.lifestyle currentSAFE_Lifestyle, l.maxlevellifestyle as highestSAFE_Lifestyle
# FROM
# 	usv_users usv
# left JOIN
#     goqii_user u on usv.goqiiUserId = u.userId
# left JOIN
#     goqii_user_extend e ON u.userid = e.userid
# LEFT JOIN
#     goqii_coach c ON u.coachid = c.coachid
# LEFT JOIN
#     goqii_expert ex ON u.expertid = ex.expertid
# left join
#     goqii_user_lifestyle_ready_data l ON u.userid = l.userid
# left join
# 	(
#     SELECT t.userId,
# 		sum(case when t.sender = 'user' then 1 else 0 end) userMsgCount,
# 		sum(case when t.sender = 'coach' then 1 else 0 end) coachMsgCount,
# 		sum(case when t.sender = 'expert' then 1 else 0 end) expertMsgCount,
#         max( case when t.sender = 'user' then date(t.date) else null end) lastUserMsg
# 		FROM goqii_coach_user_conversation t
# 		inner JOIN goqii_user u ON t.userId = u.userId
# 		where u.corporateId = 641  and t.systemMessage = 'N'
# 		group by t.userId
#     ) m ON u.userid = m.userid
# left join
# 	(
#     SELECT t.userId, count(*) attemptedCallsCount,
# 		sum(case when t.status = 'completed' then 1 else 0 end) completedCallsCount,
#         sum(case when t.callType = 'intro' and t.status = 'completed' then e.duration else 0 end) sumOfIntroCallDuration,
#         max(case when t.callType = 'intro' and t.status = 'completed' then e.duration else 0 end) maxOfIntroCallDuration,
#         max(date(t.createdtime)) lastCallDate
# 		FROM goqii_user_calls_history t
# 		inner join goqii_exotel_rel e on t.userId = e.userId
# 		inner JOIN goqii_user u ON t.userId = u.userId
# 		where u.corporateId = 641  and e.duration != 0
# 		group by t.userId
#     ) cl ON u.userid = cl.userid
# where usv.isTestUser = 'N' and usv.tags = 'Real Patient'
# """, engine)

cocUsers.head()

# 1. Select the worksheet (tab)
worksheet = sh.worksheet('userData') # get_worksheet for index

# 2. Clear existing content (optional, to avoid appending data weirdly)
worksheet.clear()

# 3. Paste the data
set_with_dataframe(worksheet, cocUsers)
